obj-$(CONFIG_TOUCHSCREEN_NT36672)   += nt36672/
obj-$(CONFIG_VITURALSAR)			+= vituralsar_driver.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_E7)       += td4310_e7/
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7)       += td4310_lansi_e7/
obj-$(CONFIG_TOUCHSCREEN_FTS_MI8953) += focaltech_touch/
obj-$(CONFIG_TOUCHSCREEN_FT5446_E6) += ft5446_e6/
obj-$(CONFIG_TOUCHSCREEN_GT9XX) += gt9xx/
obj-$(CONFIG_MACH_XIAOMI_YSL)		+= lct_tp_fm_info_e6.o