obj-$(CONFIG_TOUCHSCREEN_SYSCTL_MI8953) += ts_sysctl.o
obj-$(CONFIG_TOUCHSCREEN_NT36672)   += nt36672/
obj-$(CONFIG_VITURALSAR)			+= vituralsar_driver.o
obj-$(CONFIG_TOUCHSCREEN_TD4310_E7)       += td4310_e7/
obj-$(CONFIG_TOUCHSCREEN_TD4310_LANSI_E7)       += td4310_lansi_e7/
obj-$(CONFIG_TOUCHSCREEN_FTS_MI8953) += focaltech_touch/